### ISSUE TITLE
Implement a JSON serializer

### ISSUE THREAD

**Issue by vil1** [scalaz/scalaz-schema#18]
We should now have enough material to try and implement a first serializer.

The main idea is to implement a function like the following: 

```scala
def jsonSerializer[A](schema: Schema[A])(implicit prims: ToJson[Prim[A]]): A => JSON = ???
```
Where `ToJson` is a simple typeclass needed to convert the primitive types of the module to JSON. 
The actual `JSON` representation isn't very important for now, we can just define `type JSON = String` for the moment.

**Comment by mmenestret** [comment]
I'll try to work on that one if that's ok :)

**Comment by vil1** [comment]
Done in #26
