### ISSUE TITLE
Allow for recursive (self-referent) schemas

### ISSUE THREAD

**Issue by vil1** [scalaz/scalaz-schema#29]
We need a way to represent recursive types like: 

```scala
sealed trait Tree
final case class Node(left: Tree, right: Tree) extends Tree
final case class Leaf(label: Int)              extends Tree
```

One idea (thx @julienrf) would be to have a dedicated member in the GADT for that:
```scala
final class SchemaReference[F[_], A](ref: => F[A]) extends Schema[F, A]
```
which would allow us to use `lazy val`s or `def` to build such recursive schema, but would require interpreters implementers (that is us, most of the time) to properly handle the laziness.

```scala
lazy val tree = union(
  "Node" -+>: record(
    "left" -*>: tree :*:
    "right" -*>: tree
  ) :+:
  "Leaf" -+>: record(
    "label" -*>: prim(IntSchema)
  )
)
```

Another, more "essential" way would be to find a way to encode the "y-combinator", or some kind of fix-point, at the schema level.

**Comment by mijicd** [comment]
Since it's considered "low-hanging fruit" as per @vil1, I'll try to take care of it.

**Comment by vil1** [comment]
More precisely: "low hanging fruit hiding possible surprises" ;)
Have fun!

**Comment by GrafBlutwurst** [comment]
#54 should have closed this?
