### ISSUE TITLE
Flesh out the Schema AST

### ISSUE THREAD

**Issue by vil1** [scalaz/scalaz-schema#3]
The constructors for schemas aren't implemented yet (see [this definition](https://github.com/scalaz/scalaz-schema/blob/53c191b47e1f115c45813a467620b9fe0eac36c8/src/main/scala/SchemaModule.scala#L11) for example).

We'll probably need more constructors like the one already defined (for records fields at least).

Also, the monocle dependencies (for things like `Getter`, `Optional` and so on) isn't defined yet, it needs to be added to the `build.sbt`

**Comment by jkobejs** [comment]
I'd like to take this one.

**Comment by vil1** [comment]
As said in #14, we'll keep this issue open until we have tests for it

**Comment by vil1** [comment]
Tests have been added by #15
