### ISSUE TITLE
Flesh out the GenModule

### ISSUE THREAD

**Issue by vil1** [scalaz/scalaz-schema#6]
In order to see how far we can go with our current approach, we need to make sure the current Schema AST allows for concrete features like giving free scalacheck `Gen` instance from a schema.

That is, provided we have `Gen` instances for all the primitive types in a schema, we need to produce a `Gen` for the whole schema.

The (commented out) signature for `gen` in `modules/scalacheck/src/main/scala/GenModule.scala` might need to be adapted to fit that purpose.

**Comment by jkobejs** [comment]
I would like to take this one.

**Comment by vil1** [comment]
I think it would be highly beneficial if you were able to provide this functionality by means of a `Schema ~> Gen` natural transformation. 
Doing so will probably give us insights about ways to later generalize this to `Schema ~> F` (telling us which typeclass instances are required for `F` for example).

**Comment by vil1** [comment]
Hi @josipgrgurica, did you make any progress on this, do you need some help?

**Comment by jkobejs** [comment]
Hi @vil1, I stuck on part where I need to create record from schema and field values. I saw that record schema is defined in terms of applicative in xenomorph, should I try to add it in our record schema?

**Comment by vil1** [comment]
Well, I'm not sure you need an `Applicative[RecordSchema]` for this (but I might be wrong), what is certain though is that you'll need an `Applicative[Gen]`.

If you have written some code already, why not pushing a WIP PR (or pointing me to the corresponding branch on your own fork) so that I can take a look?

**Comment by jkobejs** [comment]
Sure, I'll push it later today.
